//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppServiceCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cluent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cluent()
        {
            this.MasterOrdersMaster = new HashSet<MasterOrdersMaster>();
            this.MasterOrdersMaster1 = new HashSet<MasterOrdersMaster>();
            this.MasterOrdersMaster2 = new HashSet<MasterOrdersMaster>();
        }
    
        public int id { get; set; }
        public string FullName { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public int idOrders { get; set; }
    
        public virtual Orders Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterOrdersMaster> MasterOrdersMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterOrdersMaster> MasterOrdersMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterOrdersMaster> MasterOrdersMaster2 { get; set; }
    }
}
