//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppServiceCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterOrdersMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterOrdersMaster()
        {
            this.Master = new HashSet<Master>();
            this.Orders1 = new HashSet<Orders>();
            this.Orders2 = new HashSet<Orders>();
            this.Orders3 = new HashSet<Orders>();
        }
    
        public int id { get; set; }
        public string Vremonta { get; set; }
        public string Stoimremon { get; set; }
        public string opisrem { get; set; }
        public string zatrelement { get; set; }
        public string detalnaxamen { get; set; }
        public string stoimDiagnos { get; set; }
        public Nullable<int> idOrders { get; set; }
        public Nullable<int> idCluent { get; set; }
    
        public virtual Cluent Cluent { get; set; }
        public virtual Cluent Cluent1 { get; set; }
        public virtual Cluent Cluent2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Master> Master { get; set; }
        public virtual Orders Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders3 { get; set; }
    }
}
