//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppServiceCenter.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceCenterEntities : DbContext
    {
        public ServiceCenterEntities()
            : base("name=ServiceCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cluent> Cluent { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<MasterOrdersMaster> MasterOrdersMaster { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Rolle> Rolle { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
